language: node_js
node_js:
  - '0.10'

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g karma
  - npm install karma-phantomjs-launcher --save-dev
  - npm install -g phantomjs --save-dev
  - bower install